### ISSUE TITLE
Tables are converted to paragraphs

### ISSUE THREAD

**Issue by pkbarbiedoll** [lgarron/clipboard.js#16]
Like the script, but was a little surprised to find that the simplest of tables: 

     <script>
    document.getElementById(\"markup-copy\").addEventListener(\"click\", function() {
      clipboard.copy({
        \"text/plain\": \"Markup text. Paste me into a rich text editor.\",
        \"text/html\": \"<i>Markup </i> <b>text</b>. Paste me into a rich text editor. <table border=1>        <tr><td>I</td><td>am</td></tr><tr><td>a</td><td>table</td></tr></table>\"
      }).then(
        function(){console.log(\"success\");},
        function(err){console.log(\"failure\", err);
      });
    });
    </script>

converted to paragraphs instead of the table: 

    <p><em>I am a </em> <strong>child record</strong>. Paste me into a rich text editor.</p>
    <p>Iam</p><p>atable</p>

Is there a way to configure so it retains tables?

**Comment by pkbarbiedoll** [comment]
Disregard, this was an issue with CKEditor, when pasting into other textboxes my table is retained.  Thanks again for the excellent script.

**Comment by lgarron** [comment]
Glad it worked out. :-)
