### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by daedalus28** [lgarron/clipboard.js#17]
It would be great to get this on bower as it is primarily a front end module.

**Comment by lgarron** [comment]
I had a bunch of hiccups, bit I think it's working now. Could you let me know if there are more issues?

**Comment by lgarron** [comment]
(In particular, I don't know if I should be setting certain default export configurations. I'd like to keep the actual source file as light as possible.

**Comment by daedalus28** [comment]
Sorry for the delayed response - we've actually moved forward with https://github.com/zenorocha/clipboard.js instead of this library and so haven't tested the bower stuff. It would be really great if you could unify your efforts as there seems to be 100% overlap here.

**Comment by lgarron** [comment]
I don't think there's 100% overlap, but I might look into it later.
(I started this library because there was nothing else around yet, but I'm glad someone else is carrying the torch.)
