### ISSUE TITLE
Create a minified version

### ISSUE THREAD

**Issue by stanleyxu2005** [lgarron/clipboard.js#19]
Although it is small enough, it'd be great to have a minified version.

**Comment by lgarron** [comment]
Do you mean like #15 or just run through a minifier?

**Comment by stanleyxu2005** [comment]
no. I meant I provide a clipboard.min.js

**Comment by Zvirja** [comment]
+1 for the clipboard.min.js

**Comment by lgarron** [comment]
There you go. I've tested the minified version in a bunch of browsers, but lemme know if it causes problems.

**Comment by Zvirja** [comment]
Thank you!
