### ISSUE TITLE
The "Can I use" link mark Safari as working from v9, but it's not listed on the readme

### ISSUE THREAD

**Issue by balazsnemeth** [lgarron/clipboard.js#34]
[Here](http://caniuse.com/#feat=clipboard) the Safari seems to be supported, but it's not listed on the readme file. Is Safari supported or not?

**Comment by lgarron** [comment]
See https://bugs.webkit.org/show_bug.cgi?id=156529

**Comment by lgarron** [comment]
Also note that document.execCommand() is only available in the upcoming
version of Safari. If they don't fix the compat bug when they ship stable,
I'll probably add a hacky workaround to this project.

**Comment by lgarron** [comment]
> I'll probably add a hacky workaround to this project.

Hacky workaround implemented in dbd90f412ade3224f020efde04c5ab84ac967fe0.
