### ISSUE TITLE
Doesn't work in callbacks

### ISSUE THREAD

**Issue by rajatnarang17** [lgarron/clipboard.js#37]
When I make a Ajax call and then use clipboard.copy('some text') in the callback function, it gives an error: 'Uncaught (in promise) Error: Unable to copy. Perhaps it's not available in your browser?'. 
Works well normally though. Kindly look into this.

Thanks

**Comment by lgarron** [comment]
Most browsers require a user gesture to directly trigger the code that copy to the clipboard (+ a few heuristics to sometimes allow it later). This library can't work around that.

Could you verify that copying without the AJAX call works?

**Comment by rajatnarang17** [comment]
Okay, Thanks!
Yes, it works without AJAX call.
