### ISSUE TITLE
The given range and the current selection belong to two different document fragments.

### ISSUE THREAD

**Issue by filoveg** [lgarron/clipboard.js#38]
I get this warning in Chrome 

> The given range and the current selection belong to two different document fragments.

Even thought the script works great, I am only copying the value of an input like so

```
	<input onclick="copyValue()" value="asdf"></input>
        
        function copyValue(){
         	clipboard.copy(event.target.value);
        }
```

**Comment by lgarron** [comment]
Yikes. This is really frustrating. :-(

We have to work around [a bug in Safari](https://bugs.webkit.org/show_bug.cgi?id=156529) where there is no selection. However, I don't know a way to use feature detection to exclude the workaround in Chrome (short of trying to copy multiple times in different ways). It's the workaround that causes this problem when your cursor has not highlighted a range.

The only options I can think of:
- Sniff the UA to detect Chrome (sounds very bad; Edge tries to pretend to be Chrome to UA sniffers)
- Try with and without the bogus selection. :-/
