### ISSUE TITLE
Get the copied clipboard data in Chrome

### ISSUE THREAD

**Issue by piu** [lgarron/clipboard.js#39]
Hi,

I am using Clipboard.js in my react application and I am copying the data to clipboard using clipboard.copy() which atually does successfully copy text but clipboard.paste() is not supported in chrome, hence I used document.execCommand('paste')  to retrieve the copied text in dummy textarea. But its not working for me. Do you have any example/ method to retrieve the data copied in clipboard.js successfully?

**Comment by lgarron** [comment]
Programmatic pasting on the open web is not supported by Chrome (else I would update `clipboard.paste()` to work).
