### ISSUE TITLE
safari on iphone or ipad，it tips "success" but did't write to the clipboard

### ISSUE THREAD

**Issue by lw-gelei** [lgarron/clipboard.js#42]
IOS Version 10+，

detail:
ipad 10.3.1 
iphone 10.3.2

**Comment by cihadsevim** [comment]
Same goes here.

**Comment by lgarron** [comment]
Yeah, I haven't figured out what happens. There is no error message in the console. :-(

**Comment by lgarron** [comment]
http://caniuse.com/#search=clipboard suggests that copying doesn't work on iOS.

I wouldn't be surprised if the API fails silently. :-/

**Comment by baijunjie** [comment]
Can't work on an iphone, But [zenorocha/clipboard.js](https://github.com/zenorocha/clipboard.js) worked normally.

**Comment by jab** [comment]
@lgarron Please update the README with the caveat that this doesn't yet work on iOS. You can link to this issue and note the "help wanted" label, so maybe someone will contribute a fix if you don't beat them to it.

**Comment by lgarron** [comment]
> @lgarron Please update the README with the caveat that this doesn't yet work on iOS. You can link to this issue and note the "help wanted" label, so maybe someone will contribute a fix if you don't beat them to it.

Happy to do that. Would you care to send a PR for the README stating that? :-)
(If not, I'll make a note to do it this weekend.)

**Comment by lgarron** [comment]
I tracked down the issue and filed a (second) bug against WebKi:
https://bugs.webkit.org/show_bug.cgi?id=177715

**Comment by rohitkandhal** [comment]
I am trying to copy a link to clipboard using the library. It succeeds 50% of the time. Other times clipboard text is empty.

**Comment by lgarron** [comment]
> I am trying to copy a link to clipboard using the library. It succeeds 50% of the time. Other times clipboard text is empty.

That sounds unpleasant. Does it alternate between success and failure, or is it random?

If it's happening under a particular set of conditions, would you mind filing a new bug with as many details as possible for me to reproduce the conditions?
