### ISSUE TITLE
copy number not work

### ISSUE THREAD

**Issue by BernardZhang** [lgarron/clipboard.js#43]
copy number not work event prompt copy successfully.  Currently solved this issue by convert number to string.

example: clipboard.copy(1) then paste and the paste content is the last copy data.

**Comment by lgarron** [comment]
It's only possible to copy strings to the clipboard in browsers right now.

I've updated the library to reject the data if it's not the right type. It might be a bit more code to explicitly convert to a string, but this should help prevent accidental misuse.
