### ISSUE TITLE
Copying MIME mappings not working with 0.3.4 version

### ISSUE THREAD

**Issue by theskull31** [lgarron/clipboard.js#44]
Hi, 
Since the update of the 0.3.4, the copy function is not working for a string.
If I do: 
clipboard.copy({
  "text/plain": "Text to copy"
});
I got this message : "Uncaught (in promise) Invalid data type. Must be string, DOM node, or an object mapping MIME types to strings."
This worked with the 0.3.3 version but not with the 0.3.4.
For the moment, I blocked the version in my project to 0.3.3.
Thanks.

**Comment by lgarron** [comment]
Looks like I introduced a typo in the object check, and forgot to test that case. :-(

I'll push a fix now.

**Comment by theskull31** [comment]
Looks good.
Thanks.
