### ISSUE TITLE
maintain a changelog

### ISSUE THREAD

**Issue by jab** [lgarron/clipboard.js#45]
I saw there were just some new releases of clipboard.js (thanks to [versioneye](https://www.versioneye.com/javascript/lgarron:clipboard.js)) and so I wanted to see what had changed since the release I'm using, but didn't see release notes anywhere. Would you be interested in maintaining some?

Thanks for your consideration and for your work on clipboard.js, big fan!

**Comment by lgarron** [comment]
I certainly can. What's the way people usually do this? Manually edit the release tags on GitHub?

**Comment by lgarron** [comment]
I've added the major change for each release at https://github.com/lgarron/clipboard.js/releases
(There was basically just one major change for each release.)

**Comment by jab** [comment]
Thanks a lot @lgarron!

For my projects, I maintain a CHANGELOG in my repo (which gets included in my docs build and published to my readthedocs.org site), and I have to manually sync it with GitHub Releases. I did open isaacs/github#882 to suggest GitHub make this better somehow -- upvote / email support@github.com with a +1 for it if you think it's a good idea?

Thanks again!
